version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
  redis:
    image: redis:6.2-alpine
    volumes:
      - redis-data:/data
volumes:
  redis-data: